extern crate diff_sync;


fn main() {
    let a = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id eleifend urna. Nam vitae venenatis velit. Donec viverra feugiat massa id molestie. Quisque a pulvinar urna. Etiam nec dui odio. Pellentesque leo diam, eleifend vitae varius eget, aliquet quis dui. Phasellus eleifend lacus velit, quis malesuada dui tincidunt ut. Etiam sit amet tellus vel tellus pretium sagittis ut a magna.

Donec sed lacinia nunc. Nulla quis mauris felis. Suspendisse pretium tellus ante, a luctus nisi posuere id. Sed fermentum fringilla nisl non imperdiet. Aliquam nisi ex, tempor sit amet elit vel, pharetra sodales libero. Morbi pulvinar bibendum finibus. Aliquam vel fringilla dolor, id finibus ante. Mauris metus turpis, vehicula nec libero sed, accumsan faucibus lectus.

Praesent sit amet dolor efficitur, interdum urna et, egestas sem. Phasellus in tortor quis dui aliquet lobortis varius ut lectus. Nulla ornare ut dolor a euismod. Nam a laoreet velit, eget ornare leo. Donec ut pulvinar leo. Morbi in auctor nisi. Proin ultrices euismod blandit. Suspendisse potenti.

Donec ultricies magna orci, vel tincidunt lorem maximus a. Ut nulla ligula, vulputate sed ipsum et, sollicitudin faucibus ex. Donec blandit ipsum in tortor auctor elementum a eget mauris. Duis aliquet massa in augue tincidunt commodo. Nam vel ipsum vel velit mattis vestibulum. Sed eget ex ac sapien pulvinar elementum ut eget enim. Mauris mattis tempus mi, id semper felis pretium eu. Vivamus ullamcorper fermentum ligula quis tincidunt. Aliquam finibus sem vel varius consequat. Suspendisse semper sapien et gravida aliquam. Praesent placerat sodales finibus.

Suspendisse auctor nisi id ligula imperdiet rhoncus. Phasellus efficitur elit id consectetur bibendum. Donec in eros consequat nunc sodales vestibulum. Donec semper justo mi, eget sollicitudin erat sagittis sit amet. Praesent lobortis auctor justo, non tristique lorem. Nam vitae tincidunt leo. Nunc volutpat convallis ante, at venenatis sem molestie sed. Sed velit nulla, malesuada suscipit purus auctor, malesuada dapibus neque. Mauris ullamcorper odio sed lectus euismod, nec pretium metus rutrum. Sed imperdiet turpis nec dui scelerisque, tincidunt aliquam leo mattis. Suspendisse potenti. Nullam eu risus elementum, luctus odio a, tempor nulla. Duis at rhoncus neque, vel pulvinar ipsum.

Ut sagittis tempor dolor ac placerat. Sed maximus ornare tempor. Ut a libero dictum, tincidunt nisl ut, feugiat nisl. Praesent placerat massa nisl, faucibus aliquet felis porta eget. Ut nec metus eget magna fringilla sagittis in ac lacus. Quisque purus orci, luctus non lacus eget, cursus posuere odio. Proin vitae tellus quis velit blandit elementum. Cras dapibus est nec tristique ultricies. Etiam pretium sem id fermentum porta.

Nunc in eros sit amet felis lobortis facilisis. Pellentesque viverra, dolor a laoreet ornare, eros dolor dignissim lacus, eget aliquet orci mi at ante. Mauris mollis magna quis felis volutpat, vel congue ex eleifend. Aenean convallis vel lacus eget interdum. Curabitur blandit hendrerit urna, id pharetra erat pellentesque in. Suspendisse quis mi nec ligula suscipit mattis. Sed fermentum quis sem non fermentum. Nunc sollicitudin fermentum placerat. Nulla porta erat ut suscipit sollicitudin. Vivamus ac nulla et felis ullamcorper tincidunt. Mauris vitae molestie odio, vitae malesuada enim. Maecenas luctus tincidunt lectus vitae sagittis. Praesent sed tincidunt sem, vel condimentum mauris.

Mauris non enim at leo convallis imperdiet. Nulla facilisi. Morbi dolor tortor, ullamcorper at mauris vestibulum, volutpat dictum ipsum. Integer nunc metus, venenatis et turpis vitae, lobortis bibendum nisl. In ut finibus orci. Donec ac ligula sed eros gravida dapibus id ac leo. Pellentesque rutrum congue mi, id rhoncus justo lobortis ut. Vivamus sit amet nisl finibus eros placerat porta vel sed elit. In sapien risus, posuere eget blandit et, congue vitae sapien. Nunc ac pellentesque nibh. Phasellus eu tellus a sapien viverra malesuada in at turpis. Nam sed nisi tincidunt, cursus sem id, vestibulum massa. Etiam sodales suscipit eros sit amet eleifend. Cras ut mollis velit. Aliquam erat volutpat. Ut id nisl tempus felis tempus rutrum.

Sed dignissim tempor tellus, eget consequat urna congue id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc iaculis facilisis lobortis. Curabitur libero mi, tristique ut enim quis, tincidunt aliquet tortor. Fusce id arcu viverra, consequat lorem vitae, aliquam tellus. Phasellus tempus ultrices ultricies. Praesent arcu lacus, lacinia ac est sit amet, iaculis pellentesque lacus.

Nullam vel eleifend mauris. Aliquam consequat sagittis eros vitae interdum. Donec et orci id felis imperdiet porttitor. Cras feugiat, dui quis facilisis feugiat, eros nulla ultrices ex, non euismod quam erat sed eros. Nulla rutrum leo in purus interdum, sit amet dapibus tellus laoreet. Morbi laoreet sollicitudin mollis. Nunc eu elit rhoncus, tincidunt turpis sit amet, dignissim eros. Nulla facilisi. Ut dui massa, congue eu lorem a, varius auctor eros. Integer pulvinar tincidunt magna vitae aliquam. Cras facilisis imperdiet condimentum. Nam sed fermentum enim. Etiam ac justo id ligula malesuada venenatis.

Aliquam condimentum varius lectus. Quisque lectus est, blandit id justo nec, ultrices consectetur ex. Suspendisse at congue arcu. Suspendisse lacinia porta tortor, eu luctus est mattis quis. Donec imperdiet congue est, quis congue erat convallis sit amet. Integer sodales, odio vel dapibus venenatis, nisl ipsum fermentum ipsum, in aliquam dolor mauris non tortor. Quisque elementum nec tortor vitae suscipit. Duis dignissim lorem nibh, vel bibendum metus vestibulum in. Pellentesque mi eros, malesuada ut felis lacinia, laoreet efficitur dui. Suspendisse non lorem posuere, vulputate justo vel, fermentum lacus.

Aenean finibus efficitur vulputate. Integer egestas hendrerit facilisis. Aliquam pretium euismod nisi, ac elementum odio tempor a. Proin consectetur felis at est lobortis posuere. Etiam eu hendrerit ex. Praesent finibus mollis erat eu congue. Ut at tellus lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin ac sollicitudin orci. In hac habitasse platea dictumst. Pellentesque quis ipsum eu libero vestibulum convallis id eu sapien.

Morbi eu posuere turpis. Mauris orci libero, dapibus pharetra est nec, dignissim efficitur elit. Vestibulum et suscipit sapien. Sed commodo, nibh vel dignissim sagittis, ligula leo tempus massa, in mollis nisi mi in sapien. Donec placerat, lectus vitae consectetur gravida, ante enim tincidunt purus, a sollicitudin enim diam at nisi. Aliquam dictum purus eget ultrices sagittis. In tempor tincidunt sem at facilisis. Nullam consectetur urna justo, eu blandit neque elementum ornare. Vivamus fermentum a dolor vel tincidunt. Nulla a mi id mauris sollicitudin vulputate. Vivamus vel erat nec justo fermentum gravida. Aliquam id dignissim urna, id ullamcorper mi. Mauris maximus sed arcu ac vehicula.

Aenean vitae leo sed mi tincidunt faucibus a nec libero. Ut pulvinar rhoncus neque ac consectetur. Aliquam ullamcorper sed massa vitae tincidunt. Nam maximus euismod enim. Aliquam sit amet orci quam. Maecenas eu lacus ultrices, feugiat tortor et, sodales enim. Morbi aliquet nunc ullamcorper metus aliquet, sed consequat eros blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis commodo enim at ex faucibus, posuere viverra risus vehicula. Fusce lobortis dui id hendrerit tincidunt. In eget orci pellentesque, lobortis nulla sagittis, placerat velit. Sed ultricies maximus neque, ut elementum nisi efficitur et. Aenean ac mollis libero.

Mauris nec ipsum viverra, porttitor urna in, placerat risus. Nam sodales magna ut lectus ultrices, a mattis augue blandit. Sed molestie ipsum quis egestas sodales. Phasellus ut congue nisi. Maecenas ipsum urna, mollis sit amet condimentum vitae, rhoncus non ligula. Nunc tempor feugiat quam in lobortis. In magna magna, scelerisque et est non, consequat ultrices dolor. Quisque tincidunt, felis vitae maximus porttitor, tellus quam tempor erat, vel faucibus augue sapien faucibus arcu. Mauris in dignissim justo, fermentum porttitor tortor. Integer elit felis, finibus sed sagittis vel, tincidunt eget est. Integer leo leo, fringilla sit amet iaculis sed, vulputate vitae metus. In id hendrerit mi. Morbi scelerisque lectus eu est mollis, eget rutrum enim rhoncus.

Aliquam varius est quam, ut hendrerit erat convallis ut. Vestibulum metus nisi, ultrices in pretium eu, rutrum et neque. Duis sem dui, tempor eget consequat non, blandit nec enim. Phasellus convallis facilisis dolor, nec consequat enim malesuada id. Aliquam justo risus, hendrerit a sollicitudin vitae, mollis non nisl. Proin aliquam ligula at ante sodales, eget vulputate ex sagittis. Cras posuere vehicula pellentesque. Fusce mattis, ipsum eu porttitor condimentum, metus dui aliquet nisi, vitae dapibus tellus risus a nisi.

Aenean eget quam elit. Integer at nulla in tellus tincidunt vulputate. Etiam tempor nisl sed fringilla lacinia. Aliquam sagittis nibh a tortor aliquet, id placerat urna sagittis. Sed condimentum mollis euismod. Ut interdum dui et varius fermentum. Sed efficitur sollicitudin lorem quis finibus.

Nullam suscipit sed nisi a commodo. Nulla in tincidunt sem. Quisque facilisis dui quis consequat blandit. Etiam consectetur vel ipsum ac cursus. In vitae mi ligula. Suspendisse dapibus tortor quis velit accumsan, in imperdiet elit tincidunt. Vivamus sit amet augue vel justo dignissim porta. In et eros ac ante gravida euismod a a erat.

Nam interdum tellus lacus, eu tempor turpis hendrerit vel. Nulla ultrices leo id risus ultrices, non cursus nunc cursus. Nulla facilisi. Vestibulum laoreet, nisi ut egestas dictum, est dui congue risus, a facilisis metus velit venenatis sapien. Donec ac blandit enim. Morbi vulputate ultrices accumsan. Donec feugiat lobortis ligula sed eleifend. Praesent non condimentum sem. Maecenas ornare, mauris nec finibus elementum, urna justo lacinia nulla, sed suscipit libero leo sit amet elit. Praesent eget lacus vitae purus congue imperdiet non eu nibh. Aliquam dignissim at sem vel convallis. Sed posuere nunc vitae aliquam elementum.

Aliquam porta malesuada euismod. Donec efficitur sagittis laoreet. Integer semper nec purus nec vehicula. Nullam lacinia augue a enim auctor volutpat. Ut eu mi finibus, rutrum lectus eu, laoreet nulla. Nulla sit amet volutpat dui. Duis sollicitudin fermentum ligula, in facilisis massa ullamcorper a. Praesent commodo gravida elit ac vehicula. Nunc in ligula convallis, tempus leo vel, ultrices ligula. Quisque rutrum lacinia mauris eget sollicitudin. Aliquam consequat enim faucibus, fermentum lacus ut, rhoncus metus.

Sed quis purus mollis lectus interdum interdum. In hac habitasse platea dictumst. Suspendisse enim libero, iaculis quis leo vel, lobortis placerat neque. Vivamus congue leo accumsan mauris dignissim accumsan. Sed consequat purus eu est lobortis malesuada. Proin gravida, est ut ultrices ultricies, erat elit vehicula diam, vitae pretium elit tellus ut justo. Donec elementum lorem sapien, et vulputate magna gravida eget. Etiam risus magna, cursus eu posuere eget, placerat at elit. Vivamus scelerisque pharetra ex, sed fringilla nisl venenatis malesuada. Integer et vulputate dolor, a condimentum mi. Quisque nec nisi a dolor fringilla euismod eget non dolor. Fusce vel vehicula nisl. Sed iaculis leo sodales magna porta pellentesque. Vivamus euismod pulvinar libero, sed tincidunt risus malesuada eget.

In accumsan vehicula condimentum. Aliquam faucibus varius viverra. Etiam vehicula ante at nisl semper mollis. Suspendisse eros sapien, blandit in quam at, malesuada pharetra ante. Duis porttitor justo ut tortor luctus dignissim. Aliquam pulvinar erat eu mi volutpat consectetur. Nulla tempor ante sit amet augue luctus, eget venenatis justo facilisis. Pellentesque eu nibh et odio luctus mattis sit amet nec erat. Sed sodales nisi at pretium dapibus.

Sed id cursus est, non auctor eros. Nullam eleifend tellus et felis vulputate, quis tempor enim vulputate. Phasellus semper vestibulum arcu, quis lacinia ante tristique sit amet. Etiam porta vulputate diam, luctus ullamcorper quam finibus vitae. Aliquam tincidunt mauris quis varius tristique. Integer id elementum augue. Nulla sit amet laoreet magna. Suspendisse potenti. Integer posuere leo nisl, sed elementum ante condimentum sit amet. Etiam eget feugiat orci. Nulla eget ante magna. Vestibulum aliquam orci eu ullamcorper venenatis. Morbi placerat et metus et tristique. Vivamus posuere feugiat urna, sed imperdiet mi lacinia sed. Donec porttitor massa laoreet tortor efficitur cursus. Donec iaculis purus eget semper pulvinar.

Nunc ut lectus ut nisl placerat consequat id sit amet tortor. Morbi ut placerat massa, at consequat velit. Fusce vel ipsum porttitor, sagittis mi in, facilisis erat. Pellentesque vulputate neque malesuada enim aliquam, eu imperdiet dolor pellentesque. Quisque varius ante eu risus consequat maximus. Aliquam vel risus luctus, bibendum risus in, ornare felis. Morbi vehicula lorem at nulla pharetra, at sodales metus pellentesque.

Fusce accumsan quam sit amet nunc posuere gravida et pretium ante. Nunc scelerisque vestibulum est non rutrum. Vestibulum ultricies tellus quis nibh porta interdum. Praesent ullamcorper ac dui ac pharetra. Vivamus at libero auctor, finibus felis placerat, volutpat lectus. Mauris sed dui vel purus bibendum congue. Fusce commodo justo id nunc accumsan luctus. Maecenas pulvinar massa.";
    let b = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id eleifend urna. Nam vitae venenatis velit. Donec viverra feugiat massa id molestie. Quisque a pulvinar urna. Etiam nec dui odio. Pellentesque leo diam, eleifend vitae varius eget, aliquet quis dui. Phasellus eleifend lacus velit, quis malesuada dui tincidunt ut. Etiam sit amet tellus vel tellus pretium sagittis ut a magna.

Donec sed lacinia nunc. Nulla quis mauris felis. Suspendisse pretium tellus ante, a luctus nisi posuere id. Sed fermentum fringilla nisl non imperdiet. Aliquam nisi ex, tempor sit amet elit vel, pharetra sodales libero. Morbi pulvinar bibendum finibus. Aliquam vel fringilla dolor, id finibus ante. Mauris metus turpis, vehicula nec libero sed, accumsan faucibus lectus.

Praesent sit amet dolor efficitur, interdum urna et, egestas sem. Phasellus in tortor quis dui aliquet lobortis varius ut lectus. Nulla ornare ut dolor a euismod. Nam a laoreet velit, eget ornare leo. Donec ut pulvinar leo. Morbi in auctor nisi. Proin ultrices euismod blandit. Suspendisse potenti.

Donec ultricies magna orci, vel tincidunt lorem maximus a. Ut nulla ligula, vulputate sed ipsum et, sollicitudin faucibus ex. Donec blandit ipsum in tortor auctor elementum a eget mauris. Duis aliquet massa in augue tincidunt commodo. Nam vel ipsum vel velit mattis vestibulum. Sed eget ex ac sapien pulvinar elementum ut eget enim. Mauris mattis tempus mi, id semper felis pretium eu. Vivamus ullamcorper fermentum ligula quis tincidunt. Aliquam finibus sem vel varius consequat. Suspendisse semper sapien et gravida aliquam. Praesent placerat sodales finibus.

Suspendisse auctor nisi id ligula imperdiet rhoncus. Phasellus efficitur elit id consectetur bibendum. Donec in eros consequat nunc sodales vestibulum. Donec semper justo mi, eget sollicitudin erat sagittis sit amet. Praesent lobortis auctor justo, non tristique lorem. Nam vitae tincidunt leo. Nunc volutpat convallis ante, at venenatis sem molestie sed. Sed velit nulla, malesuada suscipit purus auctor, malesuada dapibus neque. Mauris ullamcorper odio sed lectus euismod, nec pretium metus rutrum. Sed imperdiet turpis nec dui scelerisque, tincidunt aliquam leo mattis. Suspendisse potenti. Nullam eu risus elementum, luctus odio a, tempor nulla. Duis at rhoncus neque, vel pulvinar ipsum.

Ut sagittis tempor dolor ac placerat. Sed maximus ornare tempor. Ut a libero dictum, tincidunt nisl ut, feugiat nisl. Praesent placerat massa nisl, faucibus aliquet felis porta eget. Ut nec metus eget magna fringilla sagittis in ac lacus. Quisque purus orci, luctus non lacus eget, cursus posuere odio. Proin vitae tellus quis velit blandit elementum. Cras dapibus est nec tristique ultricies. Etiam pretium sem id fermentum porta.

Nunc in eros sit amet felis lobortis facilisis. Pellentesque viverra, dolor a laoreet ornare, eros dolor dignissim lacus, eget aliquet orci mi at ante. Mauris mollis magna quis felis volutpat, vel congue ex eleifend. Aenean convallis vel lacus eget interdum. Curabitur blandit hendrerit urna, id pharetra erat pellentesque in. Suspendisse quis mi nec ligula suscipit mattis. Sed fermentum quis sem non fermentum. Nunc sollicitudin fermentum placerat. Nulla porta erat ut suscipit sollicitudin. Vivamus ac nulla et felis ullamcorper tincidunt. Mauris vitae molestie odio, vitae malesuada enim. Maecenas luctus tincidunt lectus vitae sagittis. Praesent sed tincidunt sem, vel condimentum mauris.

Mauris non enim at leo convallis imperdiet. Nulla facilisi. Morbi dolor tortor, ullamcorper at mauris vestibulum, volutpat dictum ipsum. Integer nunc metus, venenatis et turpis vitae, lobortis bibendum nisl. In ut finibus orci. Donec ac ligula sed eros gravida dapibus id ac leo. Pellentesque rutrum congue mi, id rhoncus justo lobortis ut. Vivamus sit amet nisl finibus eros placerat porta vel sed elit. In sapien risus, posuere eget blandit et, congue vitae sapien. Nunc ac pellentesque nibh. Phasellus eu tellus a sapien viverra malesuada in at turpis. Nam sed nisi tincidunt, cursus sem id, vestibulum massa. Etiam sodales suscipit eros sit amet eleifend. Cras ut mollis velit. Aliquam erat volutpat. Ut id nisl tempus felis tempus rutrum.

Sed dignissim tempor tellus, eget consequat urna congue id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc iaculis facilisis lobortis. Curabitur libero mi, tristique ut enim quis, tincidunt aliquet tortor. Fusce id arcu viverra, consequat lorem vitae, aliquam tellus. Phasellus tempus ultrices ultricies. Praesent arcu lacus, lacinia ac est sit amet, iaculis pellentesque lacus.

Nullam vel eleifend mauris. Aliquam consequat sagittis eros vitae interdum. Donec et orci id felis imperdiet porttitor. Cras feugiat, dui quis facilisis feugiat, eros nulla ultrices ex, non euismod quam erat sed eros. Nulla rutrum leo in purus interdum, sit amet dapibus tellus laoreet. Morbi laoreet sollicitudin mollis. Nunc eu elit rhoncus, tincidunt turpis sit amet, dignissim eros. Nulla facilisi. Ut dui massa, congue eu lorem a, varius auctor eros. Integer pulvinar tincidunt magna vitae aliquam. Cras facilisis imperdiet condimentum. Nam sed fermentum enim. Etiam ac justo id ligula malesuada venenatis.

Aliquam condimentum varius lectus. Quisque lectus est, blandit id justo nec, ultrices consectetur ex. Suspendisse at congue arcu. Suspendisse lacinia porta tortor, eu luctus est mattis quis. Donec imperdiet congue est, quis congue erat convallis sit amet. Integer sodales, odio vel dapibus venenatis, nisl ipsum fermentum ipsum, in aliquam dolor mauris non tortor. Quisque elementum nec tortor vitae suscipit. Duis dignissim lorem nibh, vel bibendum metus vestibulum in. Pellentesque mi eros, malesuada ut felis lacinia, laoreet efficitur dui. Suspendisse non lorem posuere, vulputate justo vel, fermentum lacus.

Aenean fidibus efficitur vulputate. Integer egestas hendrerit facilisis. Aliquam pretium euismod nisi, ac elementum odio tempor a. Proin consectetur felis at est lobortis posuere. Etiam eu hendrerit ex. Praesent finibus mollis erat eu congue. Ut at tellus lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin ac sollicitudin orci. In hac habitasse platea dictumst. Pellentesque quis ipsum eu libero vestibulum convallis id eu sapien.

Morbi eu posuere turpis. Mauris orci libero, dapibus pharetra est nec, dignissim efficitur elit. Vestibulum et suscipit sapien. Sed commodo, nibh vel dignissim sagittis, ligula leo tempus massa, in mollis nisi mi in sapien. Donec placerat, lectus vitae consectetur gravida, ante enim tincidunt purus, a sollicitudin enim diam at nisi. Aliquam dictum purus eget ultrices sagittis. In tempor tincidunt sem at facilisis. Nullam consectetur urna justo, eu blandit neque elementum ornare. Vivamus fermentum a dolor vel tincidunt. Nulla a mi id mauris sollicitudin vulputate. Vivamus vel erat nec justo fermentum gravida. Aliquam id dignissim urna, id ullamcorper mi. Mauris maximus sed arcu ac vehicula.

Aenean vitae leo sed mi tincidunt faucibus a nec libero. Ut pulvinar rhoncus neque ac consectetur. Aliquam ullamcorper sed massa vitae tincidunt. Nam maximus euismod enim. Aliquam sit amet orci quam. Maecenas eu lacus ultrices, feugiat tortor et, sodales enim. Morbi aliquet nunc ullamcorper metus aliquet, sed consequat eros blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis commodo enim at ex faucibus, posuere viverra risus vehicula. Fusce lobortis dui id hendrerit tincidunt. In eget orci pellentesque, lobortis nulla sagittis, placerat velit. Sed ultricies maximus neque, ut elementum nisi efficitur et. Aenean ac mollis libero.

Mauris nec ipsum viverra, porttitor urna in, placerat risus. Nam sodales magna ut lectus ultrices, a mattis augue blandit. Sed molestie ipsum quis egestas sodales. Phasellus ut congue nisi. Maecenas ipsum urna, mollis sit amet condimentum vitae, rhoncus non ligula. Nunc tempor feugiat quam in lobortis. In magna magna, scelerisque et est non, consequat ultrices dolor. Quisque tincidunt, felis vitae maximus porttitor, tellus quam tempor erat, vel faucibus augue sapien faucibus arcu. Mauris in dignissim justo, fermentum porttitor tortor. Integer elit felis, finibus sed sagittis vel, tincidunt eget est. Integer leo leo, fringilla sit amet iaculis sed, vulputate vitae metus. In id hendrerit mi. Morbi scelerisque lectus eu est mollis, eget rutrum enim rhoncus.

Aliquam varius est quam, ut hendrerit erat convallis ut. Vestibulum metus nisi, ultrices in pretium eu, rutrum et neque. Duis sem dui, tempor eget consequat non, blandit nec enim. Phasellus convallis facilisis dolor, nec consequat enim malesuada id. Aliquam justo risus, hendrerit a sollicitudin vitae, mollis non nisl. Proin aliquam ligula at ante sodales, eget vulputate ex sagittis. Cras posuere vehicula pellentesque. Fusce mattis, ipsum eu porttitor condimentum, metus dui aliquet nisi, vitae dapibus tellus risus a nisi.

Aenean eget quam elit. Integer at nulla in tellus tincidunt vulputate. Etiam tempor nisl sed fringilla lacinia. Aliquam sagittis nibh a tortor aliquet, id placerat urna sagittis. Sed condimentum mollis euismod. Ut interdum dui et varius fermentum. Sed efficitur sollicitudin lorem quis finibus.

Nullam suscipit sed nisi a commodo. Nulla in tincidunt sem. Quisque facilisis dui quis consequat blandit. Etiam consectetur vel ipsum ac cursus. In vitae mi ligula. Suspendisse dapibus tortor quis velit accumsan, in imperdiet elit tincidunt. Vivamus sit amet augue vel justo dignissim porta. In et eros ac ante gravida euismod a a erat.

Nam interdum tellus lacus, eu tempor turpis hendrerit vel. Nulla ultrices leo id risus ultrices, non cursus nunc cursus. Nulla facilisi. Vestibulum laoreet, nisi ut egestas dictum, est dui congue risus, a facilisis metus velit venenatis sapien. Donec ac blandit enim. Morbi vulputate ultrices accumsan. Donec feugiat lobortis ligula sed eleifend. Praesent non condimentum sem. Maecenas ornare, mauris nec finibus elementum, urna justo lacinia nulla, sed suscipit libero leo sit amet elit. Praesent eget lacus vitae purus congue imperdiet non eu nibh. Aliquam dignissim at sem vel convallis. Sed posuere nunc vitae aliquam elementum.

Aliquam porta malesuada euismod. Donec efficitur sagittis laoreet. Integer semper nec purus nec vehicula. Nullam lacinia augue a enim auctor volutpat. Ut eu mi finibus, rutrum lectus eu, laoreet nulla. Nulla sit amet volutpat dui. Duis sollicitudin fermentum ligula, in facilisis massa ullamcorper a. Praesent commodo gravida elit ac vehicula. Nunc in ligula convallis, tempus leo vel, ultrices ligula. Quisque rutrum lacinia mauris eget sollicitudin. Aliquam consequat enim faucibus, fermentum lacus ut, rhoncus metus.

Sed quis purus mollis lectus interdum interdum. In hac habitasse platea dictumst. Suspendisse enim libero, iaculis quis leo vel, lobortis placerat neque. Vivamus congue leo accumsan mauris dignissim accumsan. Sed consequat purus eu est lobortis malesuada. Proin gravida, est ut ultrices ultricies, erat elit vehicula diam, vitae pretium elit tellus ut justo. Donec elementum lorem sapien, et vulputate magna gravida eget. Etiam risus magna, cursus eu posuere eget, placerat at elit. Vivamus scelerisque pharetra ex, sed fringilla nisl venenatis malesuada. Integer et vulputate dolor, a condimentum mi. Quisque nec nisi a dolor fringilla euismod eget non dolor. Fusce vel vehicula nisl. Sed iaculis leo sodales magna porta pellentesque. Vivamus euismod pulvinar libero, sed tincidunt risus malesuada eget.

In accumsan vehicula condimentum. Aliquam faucibus varius viverra. Etiam vehicula ante at nisl semper mollis. Suspendisse eros sapien, blandit in quam at, malesuada pharetra ante. Duis porttitor justo ut tortor luctus dignissim. Aliquam pulvinar erat eu mi volutpat consectetur. Nulla tempor ante sit amet augue luctus, eget venenatis justo facilisis. Pellentesque eu nibh et odio luctus mattis sit amet nec erat. Sed sodales nisi at pretium dapibus.

Sed id cursus est, non auctor eros. Nullam eleifend tellus et felis vulputate, quis tempor enim vulputate. Phasellus semper vestibulum arcu, quis lacinia ante tristique sit amet. Etiam porta vulputate diam, luctus ullamcorper quam finibus vitae. Aliquam tincidunt mauris quis varius tristique. Integer id elementum augue. Nulla sit amet laoreet magna. Suspendisse potenti. Integer posuere leo nisl, sed elementum ante condimentum sit amet. Etiam eget feugiat orci. Nulla eget ante magna. Vestibulum aliquam orci eu ullamcorper venenatis. Morbi placerat et metus et tristique. Vivamus posuere feugiat urna, sed imperdiet mi lacinia sed. Donec porttitor massa laoreet tortor efficitur cursus. Donec iaculis purus eget semper pulvinar.

Nunc ut lectus ut nisl placerat consequat id sit amet tortor. Morbi ut placerat massa, at consequat velit. Fusce vel ipsum porttitor, sagittis mi in, facilisis erat. Pellentesque vulputate neque malesuada enim aliquam, eu imperdiet dolor pellentesque. Quisque varius ante eu risus consequat maximus. Aliquam vel risus luctus, bibendum risus in, ornare felis. Morbi vehicula lorem at nulla pharetra, at sodales metus pellentesque.

Fusce accumsan quam sit amet nunc posuere gravida et pretium ante. Nunc scelerisque vestibulum est non rutrum. Vestibulum ultricies tellus quis nibh porta interdum. Praesent ullamcorper ac dui ac pharetra. Vivamus at libero auctor, finibus felis placerat, volutpat lectus. Mauris sed dui vel purus bibendum congue. Fusce commodo justo id nunc accumsan luctus. Maecenas pulvinar massa.";
    let c = "Hello hello abra cadabra hocus pocus";
    let d = "Hello hello abra cadabra hopus popus aliopus";
    let update1 = diff_sync::word::compare(a, b);
    let update2 = diff_sync::word::compare(c, d);
    // println!("To change: {:?}", update2);
    // let new1 = diff_sync::character::update(a.to_string(), &update1, 0);
    // let new2 = diff_sync::word::update(c.to_string(), &update2, 0);
    // println!("Original: '{}', Change: '{}', Synced: '{}'", a, b, new1);
    // println!("Original: '{}', Change: '{}', Synced: '{}'", c, d, new2);
}